version: '3'
services:
  llm-endpoint:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    env_file:
      - .env
    ports:
      - 8888:8888  # ホストマシンのポート8888を、docker内のポート8888に接続する